version: '3'

services:
    nsqlookupd:
        image: nsqio/nsq
        command: /nsqlookupd
        ports:
        - "4160:4160"
        - "4161:4161"
    nsqd:
        image: nsqio/nsq
        command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=192.168.134.123
        depends_on:
        - nsqlookupd
        ports:
        - "4150:4150"
        - "4151:4151"
    nsqadmin:
        image: nsqio/nsq
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
        depends_on:
        - nsqlookupd
        ports:
        - "4171:4171"

    # Database
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: qwe123

    redis:
        image: redis
        ports:
            - "6379:6379"

    # Database GUI
    adminer:
        image: adminer
        ports:
            - "3300:8080"

    redis-admin:
        image: rediscommander/redis-commander
        ports:
            - "3200:8081"
        environment:
            - REDIS_HOSTS=in-redis:redis:6379:0
        depends_on:
            - redis