version: '3'

services:
    nsqlookupd:
        image: nsqio/nsq
        command: /nsqlookupd
        # networks:
        #     - nsq-network
        ports:
        - "4160:4160"
        - "4161:4161"
    nsqd:
        image: nsqio/nsq
        ## ip是本機ip，如果發現不能使用NSQ可能是IP改了
        command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=192.168.124.59
        # networks:
        #     - nsq-network
        depends_on:
        - nsqlookupd
        ports:
        - "4150:4150"
        - "4151:4151"
    # nsqd2:
    #     image: nsqio/nsq
    #     ## ip是本機ip，如果發現不能使用NSQ可能是IP改了
    #     command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=192.168.124.59
    #     # networks:
    #     #     - nsq-network
    #     depends_on:
    #     - nsqlookupd
    #     ports:
    #     - "4152:4150"
    #     - "4153:4151"
    nsqadmin:
        image: nsqio/nsq
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
        # networks:
        #     - nsq-network
        depends_on:
        - nsqlookupd
        ports:
        - "4171:4171"

    # Database
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: qwe123

    redis:
        image: redis
        ports:
            - "6379:6379"

    # Database GUI
    adminer:
        image: adminer
        ports:
            - "3300:8080"

    # Database GUI phpmyadmin
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     links:
    #         - mysql
    #     environment:
    #         PMA_HOST: mysql
    #         PMA_PORT: 3306
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - ./mysql:/var/lib/mysql

    redis-admin:
        image: rediscommander/redis-commander
        ports:
            - "3200:8081"
        environment:
            - REDIS_HOSTS=in-redis:redis:6379:0
        depends_on:
            - redis

volumes:
    db_data:
        driver: "local" ## 這個不一定要打，他會預設

# networks:
#     nsq-network:
#         driver: bridge